# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: xenial
cache: packages
latex: true

before_install:
 - sudo apt-get install -y poppler-utils
r:
- devel
os:
- linux

notifications:
  email:
    recipients:
      - scjase@gmail.com
    on_success: always
    on_failure: always
